name: "Tests"

on:
  workflow_dispatch:

jobs:

  unit-tests:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install .

      - name: Execute unit tests
        run: pytest tests/test_app.py

  integration-tests:
    name: "Integration tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.9'

      - uses: hoverkraft-tech/compose-action@v2.3.0
        with:
          compose-file: docker-compose.yml

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install .

      - name: Execute integration tests
        run: pytest tests/test_integration.py
